spring:
  application:
    name: eureka
  boot:
      admin:
        client:
          url: http://localhost:8084
server:
  port: 32001
eureka:
  instance:
    hostname: server1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info