spring:
  application:
    name: zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 9411
eureka:
  client:
    service-url:
      defaultZone: http://server1:32001/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info